#! /bin/bash
#
# Sisestatud kuu numbri järgi aastaaja leidmine
read -p "Sisesta kuu number: " kuu
# kontroll kas kuu on 1 ja 2 vahel või 12
if test $kuu -gt 1 -a $kuu -lt 3 -o $kuu -eq 12
then
	echo "Praegu on talv"
# kontroll kas kuu on 3 ja 6 vahel
elif test $kuu -ge 3 -a $kuu -lt 6
then
	echo "Praegu on kevad"
# kontroll kas kuu on 6 ja 9 vahel
elif test $kuu -ge 6 -a $kuu -lt 9
then
	echo "Praegu on suvi"
# kontroll kas kuu number on 9 ja 12 vahel
elif test $kuu -ge 9 -a $kuu -lt 12
then
	echo "Praegu on sügis"
# kui sisend ei vasta ülal toodud tingimustele
else
	echo "Kas sisestatisite kuu Mayade kalendri järgi?"
fi
#GG
