#! /bin/bash
#
# Sisestatud kellaaja järgi tervitamine
read -p "Sisesta kellaeg, täistunnid: " kell
# Kontroll kas kell on 6 ja 12 vahel
if test $kell -ge 6 -a $kell -lt 12 
then
	echo "Tere hommikust"
# Kontroll kas kell on 12 ja 18 vahel
elif test $kell -ge 12 -a $kell -lt 18
then
	echo "Tere päevast"
# Kontroll kas kell on 18 ja 22 vahel
elif test $kell -ge 18 -a $kell -lt 22 
then
	echo "Tere õhtust"
# Kontroll kas kell on 22 ja 24 vahel või 0 ja 6 vahel
elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6
then
	echo "Head ööd!"
# Kui sisend ei vasta ülal toodud tingimustele
else
	echo "It's hammertime!"
fi
#GG
