#! /bin/bash
#
# Sisestatud arvu numbrite summa leidmine 
# Arvu sisse lugemine, esimese vastuse poole välja printimine ja summa defineerimine
read -p "Sisesta arv mille numbrite summat soovid leida " arv
echo -n $arv
summa=0
# While tsükkel, mis töötab niikaua kuni arv on suurem nullist
while [ $arv -ne 0 ]
do
# 10 jäägi leidmine ja seejärel 10ga jagamine
	jaak=$((arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
#Teise poole vastusest printimine
echo " numbrite summa on" $summa
#GG
