#! /bin/bash
#
# Sisestatud arvu põhjal kuu nime välja stamine
# Arvu sisse lugemine
read -p "Sisestage kuu arv mille nime eesti keeles soovite saada " arv
# Esimene pool väljundist
echo -n "See on "
# Teise poole väljundist leiab vastavalt case-le
case $arv in
	"1") echo "jaanuar";;
	"2") echo "veebruar";;
	"3") echo "märts";;
	"4") echo "aprill";;
	"5") echo "mai";;
	"6") echo "juuni";;
	"7") echo "juuli";;
	"8") echo "august";;
	"9") echo "september";;
	"10") echo "oktoober";;
	"11") echo "november";;
	"12") echo "detsember";;
	*) echo "väär sisend";;
esac
#GG
