#!/bin/bash
find /var/ -name *.log 2> /dev/null -exec wc -l '{}' \;| #leiab log failid ja loeb ära nendes olevate ridade arvu
sort -n -r| #sorib nad ridade arvu alusel
cut -f2 -d" " #kaotab lõpptulemusest ridade arvu
# lõpp
