#! /bin/bash

read -p "Päev millal lähed?" day
#Küsib päeva kunas lähed
read -p "Kui kauaks?" duration
#Küsib puhkuse pikkust
echo `expr \( $day + $duration \) % 7 `
#Arvutab välja kunas tagasi tullakse
